export const authConstants = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_SECCESS: 'LOGIN_SECCESS',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SECCESS: 'LOGOUT_SECCESS',
    LOGOUT_FAILURE:  'LOGOUT_FAILURE'

}

export const userContants = {
    USER_REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
    USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
    USER_REGISTER_FAILURE: 'USER_REGISTER_FAILURE'
}